# Generated by Django 5.0.6 on 2024-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcard',
            options={},
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_holder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Отзыв'),
        ),
    ]
