# Generated by Django 5.0.6 on 2024-06-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_paymentcard_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cloth')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_items', to='shop.order')),
            ],
        ),
    ]
