# Generated by Django 5.0.6 on 2024-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_city_order_home_order_index_order_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiditem',
            name='size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
