# Generated by Django 5.0.6 on 2024-06-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='избранное'),
        ),
    ]
