# Generated by Django 5.0.6 on 2024-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_delete_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothshot',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='clothshot',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cloth_shots', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='clothshot',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cloth_shots', verbose_name='Изображение'),
        ),
    ]
